# Generated by Django 5.2.9 on 2025-12-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
