# Generated by Django 5.2.9 on 2025-12-09 11:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_avg_rating_course_reviews_count_courreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourReview',
            new_name='CoursReview',
        ),
    ]
