# Generated by Django 5.2.9 on 2025-12-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_courreview_coursreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursreview',
            options={'ordering': ['-created_at']},
        ),
    ]
