# Generated by Django 5.2.9 on 2025-12-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_coursreview_coursereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
