# Generated by Django 5.2.9 on 2025-12-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_telegramchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramchat',
            name='user',
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='state',
            field=models.CharField(default='new', max_length=50),
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='telegramchat',
            name='chat_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
