# Generated by Django 5.2.9 on 2025-12-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_loginotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='temp_is_instructor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='temp_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
