# Generated by Django 5.2.9 on 2025-12-18 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_telegramchat_temp_is_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='telegramchat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
