# Generated by Django 5.2.9 on 2025-12-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_loginotp_user_alter_telegramchat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
